version: "3.9"

services:
  frontend:
    container_name: "frontend"
    build:
      context: "./frontend/"
      target: "prod-env"
    ports: 
      - "${FRONT_PORT}:5000"
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}

  backend:
    container_name: "backend"
    build:
      context: "./backend/"
      target: "prod-env"
    ports: 
      - "${BACKEND_PORT}:1323"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
  
  judge:
    container_name: "judge"
    build:
      context: "./judge/"
      target: "prod-env"

  db:
    container_name: "db"
    image: mysql:8.0.25
    volumes:
      - "db-store:/var/lib/mysql"
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  redis:
    container_name: "redis"
    image: redis:6.2.5
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  db-store:
